// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEs-DBHIrUhL3F8pjK_c9mNsIm2rt_z8',
    appId: '1:560462934901:web:23ceae00c53d8766fe993c',
    messagingSenderId: '560462934901',
    projectId: 'codeofcriminal-2acf9',
    authDomain: 'codeofcriminal-2acf9.firebaseapp.com',
    storageBucket: 'codeofcriminal-2acf9.appspot.com',
    measurementId: 'G-42BBFXQEL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkR0ElI-yxxOCHIu1_XbSkZAhlFxjJYUI',
    appId: '1:560462934901:android:4a9d7cd223c36921fe993c',
    messagingSenderId: '560462934901',
    projectId: 'codeofcriminal-2acf9',
    storageBucket: 'codeofcriminal-2acf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkE7kjIrjHdYKyD4k2FaryYVd6Ww3wPY',
    appId: '1:560462934901:ios:3a6349d174fb6c58fe993c',
    messagingSenderId: '560462934901',
    projectId: 'codeofcriminal-2acf9',
    storageBucket: 'codeofcriminal-2acf9.appspot.com',
    iosBundleId: 'bnsvsipc.com.bnsVsIpc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUkE7kjIrjHdYKyD4k2FaryYVd6Ww3wPY',
    appId: '1:560462934901:ios:3a6349d174fb6c58fe993c',
    messagingSenderId: '560462934901',
    projectId: 'codeofcriminal-2acf9',
    storageBucket: 'codeofcriminal-2acf9.appspot.com',
    iosBundleId: 'bnsvsipc.com.bnsVsIpc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEs-DBHIrUhL3F8pjK_c9mNsIm2rt_z8',
    appId: '1:560462934901:web:440ae13b699ebc06fe993c',
    messagingSenderId: '560462934901',
    projectId: 'codeofcriminal-2acf9',
    authDomain: 'codeofcriminal-2acf9.firebaseapp.com',
    storageBucket: 'codeofcriminal-2acf9.appspot.com',
    measurementId: 'G-JK9KPF2CST',
  );

}